name: Build and deploy ecommerce
on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: AWS CREDENTIALS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to ECR
          run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
            
        - name: Build and push docker image
          run: |
            BRANCH_NAME=${{github.ref_name}}      
            docker build -t foodapp -f Dockerfile-RDS .
            docker tag foodapp:latest ${{ secrets.ECR_REPOSITORY_URI }}/foodapprepo:$BRANCH_NAME
            docker push ${{ secrets.ECR_REPOSITORY_URI }}/foodapprepo:$BRANCH_NAME  

        - name: Deploy applications
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ubuntu
            key: ${{ secrets.SSH_KEY }}
            # options: "-o StrictHostKeyChecking=no"
            script: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
              cd /home/ubuntu/foodapp
              docker-compose -f phpmyadmin.yml up -d
              docker-compose up -d
